version: '3'

services:
  db:
    image: postgres:12.3
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    build: .
    command:
      \usr\bin\sh -c "pwd
      && ls -l
      && ./wait_for_db.sh
      && pwd"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env